### PR TITLE
Multiple Fixes #1, #2, #3, #4, #5

### LINKED ISSUE #1: Allow users to toggle moss threshold adjustments
When off sip balance the system will automatically adjust the moss health value to 90% until balance is restored. While this is neat this is something the user should have some control over. Relevant forum notes from Jovolo:

"It's permanently set to 90. By continuously I meant when I manually adjust it back down, it sets it back up to 90. It's nothing to do with my sip balance because I have my sip at 80, if I stand around and let my health/mana drop to below 90, I automatically eat moss. I've been turning moss eating on and off once I hit my regular moss threshold of 65 as a work-around for now, but it's pretty irritating."

### PR DESCRIPTION
**Pull request by zpaav**
#1 - Added in the mosshealth/mossmana and hopefully adjusted the functions to play nice.
#2 - Added in the fix for Weariness no longer focusable - Announce #4494
#3, #4, #5 - Added in the change to Dementia, Paranoia, and Hallucinations - Added as Focusable Announce #4539
- Removed the myrrh from defup from a while ago. 
- Added in the autotree to display on the wshow settings command.

*_**Just to Note, I did not mess with the adjustments on focus balance so that might need to be tweaked._\* 
- Unfortunately I can't track down the #7 issue when looking at a clean profile everything comes up right away so need more testing there. 

Enjoy!

### CODE REVIEW

**Comment by zpaav** [comment]
Want to add the settings to show on wshow quick for the moss settings and I will put another pull in.

**Comment by zpaav** [comment]
A little more documentation on what really changed since xmls are ugly to work with and have to be viewed only in raw or via mudlet in this case:

**#2, #3, #4, #5**
Grab the whole thing look at these functions/ tables:
wsys.focusAffCount() -- Should be able to see the comments in, can clean that up when you feel
wsys.tb.affc -- Look under each of the afflictions in questions will have notes at the top of the table what was changed.
wsys.tb.cures -- Look under focus lines for the additions / subtractions.

**#1** 
_Commit 3b28296_
wsys.return_defaultsettings() -- Added in mossmana and  mosshealth
wsys.mossThreshholdDown() 
wsys.mossThreshholdUp()
wsys.aeonedLost()
wsys.unaeonDiagnose()

_Commit 0d14d31_
wsys.displaySettings()

**Comment by sailgoat** [comment]
It looks like there are mudlet mapper functions present in your source file that aren't in the main branch. Did you maybe fork an older version?

**Comment by zpaav** [comment]
Initial commit was pulled from mudlet starter which included mapper and run lua code. Had to remove those in the second commit a81b6037e4495e46527d0b9fd3cf8d0c39bdc958 for reference

**Pull request merged**
